- name: ensure mysql server is installed
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
      - mysql-server
      - libmysqlclient-dev

- name: ensure mysql server started
  service: name=mysql state=started
  sudo: yes

- name: install mysql requirements for ansible
  pip: name=MySQL-python
  sudo: yes

- name: ensure mysql_db database is created
  mysql_db: name={{ database_name }} state=present
  sudo: yes
  sudo_user: "{{ database_process_user }}"

- name: ensure user has access to mysql database
  mysql_user: name={{ database_user }} password={{ database_password }} priv={{ database_name }}.*:ALL
  sudo: yes
  sudo_user: "{{ database_process_user }}"
